name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - name: db cache
        id: cache-db
        uses: actions/cache@v4
        with:
          path: .db
          key: db
      - run: yarn download-contours
        if: steps.cache-db.outputs.cache-hit != 'true'
      - run: yarn test
      - run: yarn build
